### ISSUE TITLE
How do I pass `on_attach` and `capabilities` to omnisharp?

### ISSUE THREAD

**Issue by bartoszluka** [iabdelkareem/csharp.nvim#2]
I have custom LSP mappings that work for all language servers and I would like to pass them to omnisharp using this plugin. Is this possible now?

**Comment by iabdelkareem** [comment]
Thank you for your input, @bartoszluka I'll extend the configuration to allow passing capabilities and on_attach. There's another way to add the custom mapping that I personally prefer, which is to use [LspAttach](https://neovim.io/doc/user/lsp.html#LspAttach) autocmd instead of passing the on_attach function.

e.g.,

```lua
	vim.api.nvim_create_autocmd("LspAttach", {
		callback = function(args)
			local bufnr = args.buf
			local client = vim.lsp.get_client_by_id(args.data.client_id)

			if client.name ~= "omnisharp" then
				return
			end

			vim.keymap.set("n", "gd", require("csharp").go_to_definition, { silent = true, nowait = true, noremap = true, desc = "Go to Definition", buffer = bufnr })
		end,
	})

```

**Comment by bartoszluka** [comment]
That is exactly what I ended up doing, funny we figured out the same solution to this.

**Comment by iabdelkareem** [comment]
Yes @bartoszluka  :smile: I pushed a commit which adds capabilities and on_attach to the configuration. Thank you for the suggestion ^^

**Comment by bartoszluka** [comment]
thank you!
